#!/bin/bash

cd $(dirname $0)
>log
export LOG_LEVEL=debug
2>/tmp/$$ luajit main.lua \
  --config-dir=./config \
  --dredmor-dir="dredxml" \
  --log-level=debug \
  --log-to=log \
  --log-flush \
  "$@"
cat log /tmp/$$
rm /tmp/$$
